# Generated by Django 2.0 on 2019-02-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('posted_on', models.DateField()),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posting.Platform')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicablecode',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='earned',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.DeleteModel(
            name='ApplicableCode',
        ),
        migrations.AddField(
            model_name='postlocation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.Post'),
        ),
    ]
