# Generated by Django 2.0 on 2019-03-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20190227_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
    ]
