# Generated by Django 2.0 on 2019-02-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeauthentication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Project', unique=True),
        ),
    ]
