# Generated by Django 2.0 on 2019-02-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='recieved',
            new_name='received',
        ),
    ]
