# Generated by Django 2.0 on 2019-02-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190215_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeauthentication',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Project'),
        ),
    ]
