# Generated by Django 2.0 on 2019-02-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20190215_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='received',
            new_name='percent_received',
        ),
    ]
