# Generated by Django 2.0 on 2019-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20190215_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='add_coupon_url',
            field=models.URLField(default='https://seventhgenerationsolutions.com/wp-admin/post-new.php?post_type=shop_coupon'),
            preserve_default=False,
        ),
    ]
