# Generated by Django 2.0 on 2019-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_project_add_coupon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_post_locations',
            field=models.URLField(default='https://google.com', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='add_coupon_url',
            field=models.URLField(unique=True),
        ),
    ]
