# Generated by Django 3.0 on 2020-05-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['platform', 'name']},
        ),
        migrations.AlterField(
            model_name='livepost',
            name='number_of_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livepost',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livepost',
            name='number_of_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
