# Generated by Django 3.0 on 2020-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200515_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepost',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
