# Generated by Django 3.0 on 2020-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_samplepost_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
