# Generated by Django 3.0 on 2020-05-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20200506_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.Project'),
        ),
    ]
