# Generated by Django 3.0 on 2020-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_resource_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
