# Generated by Django 3.0 on 2020-05-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20200506_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Ocean Awareness', max_length=50),
            preserve_default=False,
        ),
    ]
