# Generated by Django 3.0 on 2020-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_samplepost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('I', 'Image'), ('D', 'Document'), ('M', 'Misc')], max_length=1),
        ),
    ]
