# Generated by Django 3.0 on 2020-05-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20200508_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name']},
        ),
    ]
